name: google_search_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.0
  dotenv: ^4.1.0
  http: ^1.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_test_handler: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
